# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-2915263-franco-desktop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-3
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/common
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/utils/inc
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/ex/inc
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/mem/inc
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/debugger/inc
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/pipeline/inc
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/uart/inc
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/id/inc
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/if/inc
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/wb/inc
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips
    /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/hazard/inc
  } {
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/utils/src/adder.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/ex/src/alu.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/ex/src/alu_control.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/mem/src/data_memory.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/debugger/src/debugger.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/debugger/src/debugger_control.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/ex/src/ex.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/pipeline/src/ex_mem.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/uart/src/fifo.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/id/src/id.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/pipeline/src/id_ex.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/if/src/if.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/pipeline/src/if_id.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/if/src/instruction_memory.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/utils/src/is_not_equal.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/utils/src/is_zero.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/id/src/main_control.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/mem/src/mem.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/pipeline/src/mem_wb.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/debugger/src/memory_printer.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/mips.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/utils/src/mux.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/if/src/pc.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/debugger/src/register_printer.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/id/src/registers_bank.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/hazard/src/risk_detection.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/utils/src/shift_left.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/hazard/src/short_circuit.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/utils/src/sig_extend.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/uart/src/uart.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/uart/src/uart_brg.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/debugger/src/uart_reader.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/uart/src/uart_rx.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/uart/src/uart_tx.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/debugger/src/uart_writer.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/utils/src/unsig_extend.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/mips/wb/src/wb.v
      /home/franco/Desktop/arqui/ARQ_ICOMP_2023-TP_FINAL/vivado.src/sources/top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-2915263-franco-desktop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
